<!-- Repo root build properties. -->
<!-- Reference https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-by-directory?view=vs-2022 -->

<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

      <!-- Set folder and file values -->
    <PropertyGroup>
      <!-- Defined Files and Folders -->
      <projectNameContainsTest>$(MSBuildProjectFile.Contains('Test'))</projectNameContainsTest>
      <folder>$(MSBuildThisFileDirectory)</folder>
      <folder>$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))</folder>

      <buildpropsfolder>$([MSBuild]::GetPathOfFileAbove('Directory.Build.props'))</buildpropsfolder>
      <thisfileFolder>$(MSBuildThisFileDirectory)</thisfileFolder>
      <propsFolder>$(MSBuildThisFileDirectory)build/</propsFolder>
      <GlobalPropsFile>$(propsFolder)global.Build.props</GlobalPropsFile>
      <TestPropsFile>$(propsFolder)test.Build.props</TestPropsFile>
      <PackagesPropsFile>$(propsFolder)Directory.Packages.props</PackagesPropsFile>

      <!-- Need to properly find the repo root and makes this relative. -->
      <buildOutputFolder>$(MSBuildThisFileDirectory)/build_output</buildOutputFolder>

      <!-- Relocatd the packages output so they can be easily uploaded to NuGet-->
      <PackageOutputPath>$(buildOutputFolder)/packages/</PackageOutputPath>
    </PropertyGroup> 

        <!-- Nuget management -->
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true </ManagePackageVersionsCentrally>
        <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
          <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>

    </PropertyGroup>


  <!-- Enable features - file nesting.-->
    <ItemGroup>
    <ProjectCapability Include="ConfigurableFileNesting" />
    <ProjectCapability Include="ConfigurableFileNestingFeatureEnabled" />
    </ItemGroup>

    <!-- Imports other build file pieces-->
    <Choose>
        <When Condition="'$(IsTestProject)'==''">
    <PropertyGroup>
        <IsTestProject>false</IsTestProject>
        <IsTestProject Condition="'$(projectNameContainsTest)'=='true'">true</IsTestProject>
    </PropertyGroup>
        </When>
    </Choose>

  <Import Project="$(GlobalPropsFile)" />
  <Import Project="$(PackagesPropsFile)" />
   <!-- Include test props file for test projects -->

        <Import Condition="'$(IsTestProject)'=='true'" Project="$(TestPropsFile)"/>

</Project>

