using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text.RegularExpressions;


/// <summary>
///   <br />
/// </summary>
/// <autogeneratedoc />
internal static class SearchStringAnalyzer
{


    /// <summary>
    /// <see cref="Regex"/> to detect wildcards at start and end
    /// </summary>
    /// <autogeneratedoc />
    private static readonly Regex _detectStartEndWildcards = new Regex(@"(?<endsWith>^([\*%]{1,}))|(?<startsWith>([\*%]{1,}$))", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    /// <summary>
    /// <see cref="Regex"/> to detect wildcards In the string
    /// </summary>
    /// <autogeneratedoc />
    private static readonly Regex _detectwildcards = new Regex(@"[\*%]{1,}", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    /// <summary>
    /// <see cref="Regex"/> to detect non-wildcard characters
    /// </summary>
    /// <autogeneratedoc />
    private static readonly Regex _findNonWildcards = new Regex(@"[^\*%]{1,}", RegexOptions.IgnoreCase | RegexOptions.Compiled);

    /// <summary>
    /// Analyzes the search string to determine required action
    /// </summary>
    /// <param name="searchString">The search string.</param>
    /// <returns></returns>
    /// <autogeneratedoc />
    internal static SearchStringAnalysisResult AnalyzeSearchString(string? searchString)
    {
        // All flags are false In the analysis object.
        var analysis = new SearchStringAnalysisResult(searchString);


        if (searchString is null) // Null? Can we leave early with defaults?
        {
            analysis.SearchStringIsNull = true;
            return SetSearchMethod();
        }

        //  whitespace?
        analysis.SearchStringIsWhitespace = (string.IsNullOrWhiteSpace(searchString) && !analysis.SearchStringIsNull);

        // Empty?
        analysis.SearchStringIsEmpty = (string.IsNullOrEmpty(searchString) && !analysis.SearchStringIsNull);

        // Leave if there is nothing to analyze futher.
        if (analysis.SearchStringIsEmpty || analysis.SearchStringIsWhitespace)
            return SetSearchMethod();

        // Wildcard analysis

        // Detect starting or ending wildcards.
        var startEndMatches = _detectStartEndWildcards.Matches(searchString).Cast<Match>();
        analysis.StartsWith = startEndMatches.Any(m => m.Groups["startsWith"].Success);
        analysis.EndsWith = startEndMatches.Any(m => m.Groups["endsWith"].Success);

        // String the start and end wildcards.
        searchString = searchString.Trim('*', '%');
        analysis.SearchString = searchString;

        // If there are zero characters here, this is just a wildcard start and end string
        if (searchString.Length == 0)
        {
            analysis.HasWildcards = true; // flag wildcards found and we're done.
            return SetSearchMethod();
        }

        // Analyze the rest of the string composition.
        var remainderContainsWildcards = _detectwildcards.IsMatch(searchString);
        analysis.HasNonWildcards = _findNonWildcards.IsMatch(searchString);
        analysis.HasWildcards = analysis.StartsWith || analysis.EndsWith || remainderContainsWildcards;

        // If there are no wildcards left We're done.
        if (!remainderContainsWildcards)
        {
            SetSearchMethod();
            return analysis;
        }

        // Force all the wildcards to a "%" character. TODO check this decision.
        // This is a contains situation.
        searchString = _detectwildcards.Replace(searchString, "%");
        analysis.SearchString = searchString;
        analysis.Contains = true;

        SetSearchMethod();
        return analysis;
        /// <summary>
        /// Sets the search type based on the detection process results.
        /// </summary>
        /// <exception cref="InvalidOperationException"></exception>
        /// <autogeneratedoc />
        SearchStringAnalysisResult SetSearchMethod()
        {
            if (analysis.SearchStringIsNull) // Nulls use == comparison
            {
                analysis.SearchComparisonType = SearchComparisonTypes.Equals; // Where item.Property.Equals("search")
                return analysis;
            }


            if (!analysis.HasNonWildcards) // after all wildcards are removed there's nothing to match.
            {
                analysis.SearchComparisonType = SearchComparisonTypes.NoOp; // Where (True)
                return analysis;
            }

            // there are search characters, identify the best search pattern.

            if (!analysis.HasWildcards)
            {
                analysis.SearchComparisonType = SearchComparisonTypes.Equals; // Where item.Property.Equals("search")
                return analysis;
            }


            if (analysis.Contains || (analysis.StartsWith && analysis.EndsWith))
            {
                // --> item.Property.Contains(searchValue)
                analysis.SearchComparisonType = SearchComparisonTypes.Contains; // Where item.Property.contains("value")
                return analysis;
            }

            if (analysis.StartsWith)
            {
                // --> item.Property.StartsWith(searchValue)
                analysis.SearchComparisonType = SearchComparisonTypes.StartsWith; // Where item.Property.StartsWith("search")
                return analysis;
            }

            if (analysis.EndsWith)
            {
                // --> item.Property.EndsWith(searchValue)
                analysis.SearchComparisonType = SearchComparisonTypes.EndsWith; // Where item.Property.EndsWith("search")
                return analysis;
            }

            // Should Never get here.
            throw new InvalidOperationException();
        }
    }
}

