using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


/// <summary>
/// Specifies the types of match for the implementation
/// </summary>
/// <remarks> Actual method name text used In some of the clauses to build linq statment e.g. starts with..</remarks>
public enum SearchComparisonTypes
{
    /// <summary>
    /// property equals value
    /// </summary>
    /// <remarks>
    /// Where item.Property.Equals("value")
    /// </remarks>
    /// 
    /// 
    Equals,
    /// <summary>
    /// Starts with text
    /// </summary>
    /// <remarks>
    /// Where item.Property.StartsWith("value")
    /// </remarks>
    /// <autogeneratedoc />
    StartsWith,
    /// <summary>
    /// Ends with text
    /// </summary>
    /// <remarks>
    /// Where item.Property.EndsWith("value")
    /// </remarks>
    /// <autogeneratedoc />
    EndsWith,
    /// <summary>
    /// Applies contains search
    /// </summary>
    /// <remarks>
    /// Where item.Property.Contains("value")
    /// </remarks>
    /// <autogeneratedoc />
    Contains,
    /// <summary>
    /// No-operation is performed and evaluates to <see langword="true"/>
    /// </summary>
    /// <remarks>
    /// Where <see langword="true"/>
    /// </remarks>
    /// <autogeneratedoc />
    NoOp
}
