using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/// <summary>
/// Stores the search string analysis, reducing the parameter count.
/// </summary>
public class SearchStringAnalysisResult
{
    /// <summary>
    /// Modified, cleaned processed string.
    /// </summary>
    /// <autogeneratedoc />
    public string? SearchString = default;

    /// <summary>
    /// The original search string
    /// </summary>
    /// <autogeneratedoc />
    public string? OriginalSearchString = default;

    /// <summary>
    /// The search string is null
    /// </summary>
    /// <autogeneratedoc />
    public bool SearchStringIsNull = default;

    /// <summary>
    /// The search string is Empty
    /// </summary>
    /// <autogeneratedoc />
    public bool SearchStringIsEmpty = default;

    /// <summary>
    /// The search string is whitespace only
    /// </summary>
    public bool SearchStringIsWhitespace = default;

    /// <summary>
    /// <see langword="true"/> for starts with search.
    /// </summary>
    /// <autogeneratedoc />
    public bool StartsWith = default;
    /// <summary>
    /// <see langword="true"/> for ends with search.
    /// </summary>
    /// <autogeneratedoc />
    public bool EndsWith = default;
    /// <summary>
    /// Searches for contains text.
    /// </summary>
    /// <autogeneratedoc />
    public bool Contains = default;
    /// <summary>
    /// Wildcards were detected in the original search string during analysis.
    /// </summary>
    /// <autogeneratedoc />
    public bool HasWildcards = default;
    /// <summary>
    /// New text has non-wildcard characters.
    /// </summary>
    /// <autogeneratedoc />
    public bool HasNonWildcards = default;
    /// <summary>
    /// Type of <see cref="SearchComparisonTypes"/> to apply.
    /// </summary>
    /// <autogeneratedoc />
    public SearchComparisonTypes SearchComparisonType = SearchComparisonTypes.Equals;


    /// <summary>
    /// Initializes a new instance of the <see cref="SearchStringAnalysisResult"/> struct.
    /// </summary>
    /// <param name="searchString">The search string.</param>
    /// <autogeneratedoc />
    public SearchStringAnalysisResult(string? searchString)
    {
        OriginalSearchString = searchString;
    }
}