using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.CompilerServices;


/// <summary>
/// Build Expression based on analysis of the wildcard string to target and the properties selected to target
/// </summary>
/// <remarks>
/// Uses a cache of expressions to reduce expression build time.
/// An expression visitor replaces the target text and target object in the composed expression. Used by the <see cref="WildCard{TSearch}"/> class.
/// </remarks>
internal class SearchExpressionBuilder
{

    /// <summary>
    /// <see langword="true"/> expression
    /// </summary>
    /// <autogeneratedoc />
    [NotNull]
    private readonly static ConstantExpression _trueExpression = Expression.Constant(true);

    /// <summary>
    /// <see langword="true"/> expression
    /// </summary>
    /// <autogeneratedoc />
    [NotNull]
    private readonly static ConstantExpression _falseExpression = Expression.Constant(false);

    /// <summary>
    /// Defines a Null String expression.
    /// </summary>
    [NotNull]
    private readonly static ConstantExpression _nullExpression = Expression.Constant(null);

    /// <summary>
    /// New string placeholder Expression - updated before execution.
    /// </summary>
    /// <autogeneratedoc />
    [NotNull]
    private readonly static ConstantExpression _searchString = Expression.Constant(nameof(_searchString), typeof(string));

    /// <summary>
    /// Cache of target term expressions
    /// Contains Expressions e.g. SearchObject.PropertyString.StartsWith(_searchString)
    /// </summary>
    /// <remarks>
    /// If queries are continously changing the wildcard search string, this could bloat.
    /// </remarks>
    [NotNull]
    private static readonly IMemoryCache _searchTermCache = new MemoryCache(
        new MemoryCacheOptions
        {
            SizeLimit = 100
        });


    private static readonly TimeSpan defaultCacheLifetime = TimeSpan.FromSeconds(20);




    //  
    /// <summary>
    // Build the property accessor expression. - generates part of the where clause.
    /// </summary>
    /// <typeparam name="TSearch">The type of the search.</typeparam>
    /// <param name="propertyExpression">The property expression.</param>
    /// <param name="searchType">Type of the search.</param>
    /// <returns></returns>
    /// <remarks>
    /// The calling party is building the bigger expression and is responsible for short circuiting testing against a null property."/>
    /// <remarks
    private static Expression BuildPropertySearchTerm<TSearch>(MemberExpression propertyExpression, SearchStringAnalysisResult analysis)
    {
        // The searchstring is key to re-usability of this expression.
        string cacheKey = $"{typeof(TSearch)},{propertyExpression},{analysis.SearchComparisonType}, {analysis.SearchString}";

        return _searchTermCache.GetOrCreate<Expression>(cacheKey,
            (e) => buildTerm(), new MemoryCacheEntryOptions
            {
                SlidingExpiration = defaultCacheLifetime,
                Size = 1
            }
                  )!;

        // Called when term is not in the cache.

        Expression buildTerm()
        {
            // NULL Testing.
            if (analysis.SearchStringIsNull) // Is the wildcard is null?, exploit this not changing until the wildcard changes.
             return Expression.Equal(propertyExpression, _nullExpression); // Both null?

            // Detailed term building is done here based on the wildcard analysis.

            return 
                analysis.SearchComparisonType switch
                {
                    
                    SearchComparisonTypes.NoOp => _trueExpression, // Analysis says this is true, no action required
                    SearchComparisonTypes.Equals => Expression.Equal(propertyExpression, _searchString), // Equals " _ searchString" constant replaced later.
                    _ => // object.property.<method> will fail if property is null!
                        Expression.Condition(
                            // Is the property null?.
                            Expression.Equal(propertyExpression, _nullExpression), _falseExpression // Then its false because _searchstring is not null
                            // Now its safe to next level test using property method calls
                            ,Expression.Call(
                                propertyExpression,
                                analysis.SearchComparisonType.ToString(), // Method name to call also the comparison type to execute.
                                new Type[] { },
                        new Expression[] { _searchString }
                        ))
                };
        }
        ;
    }

    /// <summary>
    /// Builds a function based on the search paramaters for a generic target.
    /// </summary>
    /// <typeparam name="TSearch">The type of the object we are searching or querying.</typeparam>
    /// <param name="propertyExpressions">The property expressions.</param>
    /// <param name="analysis">The analysis.</param>
    /// <returns></returns>
    public static Expression<Func<TSearch, bool>> BuildSearchExpression<TSearch>(
            IEnumerable<MemberExpression> propertyExpressions,
            SearchStringAnalysisResult analysis)
    {

        var searchTarget = Expression.Parameter(typeof(TSearch), "searchTarget"); // parameter replaced later with the object being searched.


        Expression compareExpression;


        if (analysis.SearchComparisonType == SearchComparisonTypes.NoOp) // No target filter applied at all createing where (true)
        {
            compareExpression = _trueExpression; // We all match.
            return buildLambda(); // Nothing to do here.
        }

        // Build up the propertyaccessors 
        Expression? propertyTerms = default;
        foreach (var accessor in propertyExpressions)
        {
            if (propertyTerms is null) // Initialize with the first term.
            {
                propertyTerms = BuildPropertySearchTerm<TSearch>(accessor, analysis);
                continue;
            }
            // Combine the terms with OrElse.
            propertyTerms = Expression.OrElse(propertyTerms, BuildPropertySearchTerm<TSearch>(accessor, analysis));
        }

        ArgumentNullException.ThrowIfNull(propertyTerms,"No properties specified." );

        compareExpression = propertyTerms;

        compareExpression = new PrepareStatementVisitor(searchTarget, analysis.SearchString).Visit(compareExpression); // update the search  expression with paramters for target target and the target string.


        return buildLambda();

            // Helps us exit early.
            Expression<Func<TSearch, bool>> buildLambda()
            {

                // This is a property search function so we never allow the search target to be null.
                
                compareExpression = Expression.AndAlso(Expression.NotEqual(searchTarget, _nullExpression), compareExpression); // Target != null AND Also conditions.

                return (Expression<Func<TSearch, bool>>)Expression.Lambda(compareExpression, searchTarget); // build a parameterized filter clause.
            }
        }


    #region Prepare expression visitor


    /// <summary>
    /// Replaces the target parameter and the target value In an expression
    /// </summary>
    /// <remarks> similar concept to a SQL prepare statement detecting placeholders and replacing them</remarks>
    /// <seealso cref="System.Linq.Expressions.ExpressionVisitor" />
    private class PrepareStatementVisitor : ExpressionVisitor
    {
        private readonly ParameterExpression newParameterValue;
        private readonly ConstantExpression newSearchStringValue;

        public PrepareStatementVisitor(
            ParameterExpression newParameter,
            string? searchString
            )
        {
            newParameterValue = newParameter;
            newSearchStringValue = Expression.Constant(searchString, typeof(string));
        }

        protected override Expression VisitParameter(ParameterExpression node)
        {
            return newParameterValue;
        }

        protected override Expression VisitConstant(ConstantExpression node)
        {
            if (node == _searchString)
                return newSearchStringValue;

            // Ignore other terms. (e.g. true, false)
            return node;


        }

    }

    #endregion Prepare expression visitor


    #region Simple search builders for String based wildcard search - no objects and properties

    /// <summary>
    /// Builds a function to target a string for a wildcard target string.
    /// </summary>
    /// <param name="wildcardString">The wildcard string pattern to target for</param>
    /// <returns> <see cref="Func{string, bool}"/> </returns>
    public static Expression<Func<string?, bool>> BuildWildcardSearchExpression(string? wildcardString) => BuildWildcardSearchExpression(SearchStringAnalyzer.AnalyzeSearchString(wildcardString));

    /// <summary>
    /// Builds the wildcard target function.
    /// </summary>
    /// <param name="analysis">The analysis of the requested wildcard search string.</param>
    /// <returns></returns>
    public static Expression<Func<string?, bool>> BuildWildcardSearchExpression(SearchStringAnalysisResult analysis)
    {
        var target = ParameterExpression.Parameter(typeof(string), "target");
        var searchString = Expression.Constant(analysis.SearchString, typeof(string));

        Expression compareExpression;


        if (analysis.SearchStringIsNull) // null target, so short circuit to a null test.
        {
            compareExpression = Expression.Equal(target, _nullExpression); // Are they both null??
            return buildLamba();
        }

        // Build the optimized expression possibly with a method call.
        compareExpression =
            analysis.SearchComparisonType switch // New logic function body
            {
                SearchComparisonTypes.NoOp => _trueExpression, // Always return true
                SearchComparisonTypes.Equals => Expression.Equal(target, searchString), // target.Equals(searchstring)
                _ =>
                // We are calling a method on the target, so gaurd against null values.
                Expression.Condition(Expression.Equal(target, _nullExpression), _falseExpression // We tested for wildcard, so this is false
                ,Expression.Call(
                        target, // value to invoked method on  targ.Method(searchString)
                        analysis.SearchComparisonType.ToString() // Method name to call also the comparison type to execute.
                        , null // Not a generic method
                        , searchString) // parameter
                )
            };

        return buildLamba();

        // Helps early exits and compiles the funtion.
        Expression<Func<string?, bool>> buildLamba()
            => Expression.Lambda<Func<string?, bool>>(compareExpression, target);
    }
    #endregion
}

