<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>System</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Update="readme.md">
      <PackagePath>.</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

</Project>
